### ISSUE TITLE
GitHub SaaS Integration with Internal Jira Server

### ISSUE THREAD

**Issue by AdilBNC** [dduzgun-security/github-enterprise-cloud-configuration#3]
Let's not forget to address that case a weill since it can become a blocker because of the internal use of Tempo and the Flow time in Jira.
Reference: https://confluence.atlassian.com/adminjiraserver/linking-a-bitbucket-or-github-repository-with-jira-938846899.html

**Comment by dduzgun-security** [comment]
A communication to internal services can be done with GitHub self-hosted runners.
